version: '3.8'
services:
  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    restart: unless-stopped
    
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: unless-stopped
